nomad:
  ros__parameters:
    model_name: "nomad"
    model_weights_path: "/home/adith/Git/nomad_ws/src/nomad/deploy/model_weights/nomad.pth"
    model_config_path: "/home/adith/Git/nomad_ws/src/nomad/train/config/model.yaml"
    topomap_images_dir: "/home/adith/Git/nomad_ws/src/nomad/preprocessing/topomap"
    topomap_dir: "/home/adith/Git/nomad_ws/src/nomad/preprocessing/topomap/ex10"
    waypoint: 2
    goal_node: -10
    close_threshold: 3
    radius: 5
    skip: 5
    tolerence: 5
    num_samples: 8
    v_max: 0.5
    w_max: 0.5
    hz: 4.0
    graph_hz: 0.33
    n_value: 0
